name: el_sueno_comunista
description: "App de economía colaborativa vecinal - El Sueño Comunista"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  firebase_messaging: ^15.1.6
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0
  
  # Navigation
  go_router: ^14.6.2
  
  # Location
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  
  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  
  # Utils
  intl: ^0.20.2
  image_picker: ^1.1.2
  dartz: ^0.10.1
  shared_preferences: ^2.3.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
